
version: "1"

dev_mode: true
listen_addr: "0.0.0.0:3002"
log_level: "debug"
graphql_path: "/graphql"

execution_config:
  file:
    path: "/app/router.json"
    watch: false

websocket:
  enabled: true
  forward_initial_payload: true
  forward_upgrade_headers:
    enabled: true

automatic_persisted_queries:
  enabled: true

subgraph_error_propagation:
  propagate_status_codes: true
  mode: pass-through
  default_extension_code: DOWNSTREAM_SERVICE_ERROR
  omit_extensions: false
  omit_locations: true
  attach_service_name: true # Attach the service name to the error
  allowed_extension_fields: # Propagate additional fields from subgraphs
    - "code"

# engine:
  # enable_net_poll: false